name: xls_view
description: "A modern Flutter XLS file reader app with clean UI and file management features."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^14.2.7
  
  # File Operations
  file_picker: ^8.0.7
  path_provider: ^2.1.4
  
  # XLS/XLSX Processing
  excel: ^4.0.6
  
  # UI Components
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  
  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  intl: ^0.19.0
  path: ^1.9.0
  
  # Sharing
  share_plus: ^9.0.0
  
  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
